/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#bbc5eb",
        "on-surface-variant": "#bccac4",
        "on-tertiary-fixed": "#0f1a37",
        "surface-container-lowest": "#0c0c1f",
        "surface-container-highest": "#333348",
        "surface": "#111125",
        "on-primary-container": "#003026",
        "background": "#111125",
        "secondary": "#ecb2ff",
        "surface-container-low": "#1a1a2e",
        "on-error": "#690005",
        "outline": "#86948e",
        "tertiary-fixed": "#dae1ff",
        "primary-fixed-dim": "#65dabc",
        "primary-container": "#1ca388",
        "secondary-container": "#6f258e",
        "primary": "#65dabc",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#ecb2ff",
        "on-secondary-container": "#e59dff",
        "on-secondary-fixed": "#320047",
        "on-primary-fixed-variant": "#005142",
        "on-tertiary-container": "#1e2946",
        "on-surface": "#e2e0fc",
        "primary-fixed": "#82f7d8",
        "surface-container-high": "#28283d",
        "on-tertiary": "#252f4d",
        "on-secondary": "#520071",
        "on-error-container": "#ffdad6",
        "surface-variant": "#333348",
        "outline-variant": "#3d4945",
        "surface-bright": "#37374d",
        "inverse-on-surface": "#2f2e43",
        "tertiary-container": "#8590b3",
        "on-primary-fixed": "#002019",
        "surface-container": "#1e1e32",
        "inverse-surface": "#e2e0fc",
        "surface-dim": "#111125",
        "inverse-primary": "#006b58",
        "tertiary-fixed-dim": "#bbc5eb",
        "surface-tint": "#65dabc",
        "on-secondary-fixed-variant": "#6c228c",
        "on-background": "#e2e0fc",
        "on-primary": "#00382d",
        "on-tertiary-fixed-variant": "#3b4665",
        "error": "#ffb4ab",
        "secondary-fixed": "#f8d8ff"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
