
# ===============================
# Server Configuration
# ===============================
server.port=8080




spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/discussion_forum1}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:sami@008}
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=${JWT_SECRET:YourSuperSecretKeyForJWTAuthenticationMustBeAtLeast256BitsLongForHS256Algorithm2024}
jwt.expiration=${JWT_EXPIRATION:86400000}


admin.username=${INITIAL_ADMIN_USERNAME:admin}
admin.email=${INITIAL_ADMIN_EMAIL:admin@forumhub.com}
admin.password=${INITIAL_ADMIN_PASSWORD:admin123}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dnnwtssf8}
cloudinary.api-key=${CLOUDINARY_API_KEY:145585888673846}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:i0vBxUT070uK1dgySuxxs4EWs10}


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Gemini API Configuration
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
gemini.api.key=AIzaSyA6m0YMDKkXcXOJ4wFAeSKtuqcOX0hi06U